### List all messages
GET http://localhost:3000/messages

### Create a new message
POST http://localhost:3000/messages
Content-Type: application/json

{
  "text": "Hello, World3!"
}

### Get a specific message by ID
GET http://localhost:3000/messages/1762990246793

### Update a specific message by ID
PUT http://localhost:3000/messages/1762990246793
Content-Type: application/json

{
  "text": "Updated message text2"
}

### Delete a specific message by ID
DELETE http://localhost:3000/messages/1762990246793